// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements getHealth operation.
//
// Health.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context, params GetHealthParams) (r GetHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostHealth implements postHealth operation.
//
// Health.
//
// POST /health
func (UnimplementedHandler) PostHealth(ctx context.Context, req *HealthRequestSchema) (r PostHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Test implements test operation.
//
// Test.
//
// POST /test
func (UnimplementedHandler) Test(ctx context.Context, req *TestReq) (r TestRes, _ error) {
	return r, ht.ErrNotImplemented
}
