// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetHealthParams is parameters of getHealth operation.
type GetHealthParams struct {
	// Message.
	Message string
}

func unpackGetHealthParams(packed middleware.Parameters) (params GetHealthParams) {
	{
		key := middleware.ParameterKey{
			Name: "message",
			In:   "query",
		}
		params.Message = packed[key].(string)
	}
	return params
}

func decodeGetHealthParams(args [0]string, argsEscaped bool, r *http.Request) (params GetHealthParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: message.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "message",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Message = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
