// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/HealthRequestSchema
type HealthRequestSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HealthRequestSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HealthRequestSchema) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/HealthResponseSchema
type HealthResponseSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HealthResponseSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HealthResponseSchema) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/OKResponseSchema
type OKResponseSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *OKResponseSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *OKResponseSchema) SetMessage(val string) {
	s.Message = val
}

func (*OKResponseSchema) testRes() {}

type TestBadRequest Error

func (*TestBadRequest) testRes() {}

type TestForbidden Error

func (*TestForbidden) testRes() {}

type TestNotFound Error

func (*TestNotFound) testRes() {}

type TestReq struct {
	// Status.
	Status int `json:"status"`
}

// GetStatus returns the value of Status.
func (s *TestReq) GetStatus() int {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *TestReq) SetStatus(val int) {
	s.Status = val
}

type TestUnauthorized Error

func (*TestUnauthorized) testRes() {}
