services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
    volumes:
      - ../:/app
    restart: always
  